/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import basiclibrary.Library;
import org.junit.Test;
import static org.junit.Assert.*;


public class LibraryTest {

   @Test
    public void testRollingDice() {
     //check the length of the newArray
     int[] array = Library.roll(3);
     assertEquals("this is the result []", array.length, 3);
     for (int i = 0; i < array.length; i++) {
       assertTrue(array[i] >= 1 && array[i] <= 6);
     }
   }

     @Test
     public void testRollingDiceZero(){
       //check the length of the newArray
       int[] array = Library.roll(0);
       assertEquals("this is the result []", array.length, 0);
       for (int i = 0; i < array.length; i++) {
         assertTrue(array[i]>=1 && array[i]<=6);
       }
    }
      @Test
      public void testContainsDuplicates(){
       assertTrue(Library.containsDuplicates(new int[]{1,2,3,4,1}));
    }

      @Test
      public void testContainsDuplicatesZero(){
        assertFalse(Library.containsDuplicates(new int[]{}));
  }

      @Test
      public void testCalculatingAverages(){
        int[] inputArr = { 10, 10, 20, 20};
        int expected = 15;
        assertEquals("it should give back the average in the array", expected, Library.calculatingAverages(inputArr));
      }

      @Test
        public void testarraysOfArrays(){
        //calculate the average value for each array
        //return the array of the lowest value

      }

}

