/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import java.util.Random;
//i got multiple helps from michelle, jon, quang, jeff to figure out how to generate numbers, rolling dice and intelliJ prob

public class Library {
    //main method -
    public static int[] roll (int n){
        int diceOne = 1;
        int diceTwo = 6;
        Random rand = new Random();
        int[]newArray = new int[n];


        for(int i = 0; i < n; i++){
            //generate int 1 and 6 and put it in the array
            int randNum = rand.nextInt((diceTwo - diceOne) + 1) + diceOne;
            //put it into the array
            newArray[i] = randNum;
            //repeat
        }
        return newArray;
    }
    // i got quangs help here to run my test
    public static boolean containsDuplicates (int[] arr){
     for (int i = 0; i < arr.length-1; i++){
        for (int j = 1; j < arr.length; j++) {
            if (arr[i] == arr[j]){
                return true;
            }
        }
     }
     return false;
    }

    public static int calculatingAverages(int[] arr) {
        int sum = 0 ;
        int average = 0;

        for (int value : arr) {
            sum += value;
            average = sum / arr.length;
        }
        return average;
    }

    public static int arraysOfArrays (int[][]arr){
        //given an array of arrays  calculate the average value for each array and return the array with the lowest average
        int arrAverage
        double lowestAverage = calculatingAverages(arr[0]);
                for (int i =1; i>arr.length; i++);
                lowestAverage =
    }


}
----
public boolean  someLibraryMethod(){
    ArrayList<Integer>
        }


        HashMAp <String, Integer> shoeSizes = new HashMap<>();
        shoeSizes.put("Michelle", 9)